### ISSUE TITLE
Create GitHub Pages as a example

### ISSUE THREAD

**Issue by iamchathu** [birz4man/Personal-Template#1]
read more at https://pages.github.com/

**Comment by frkn-aydn** [comment]
I can create github page but is that necessary ? Because this is very simple and very basic template.

**Comment by iamchathu** [comment]
So others can easily preview the site. And easy to fork and create their one too

**Comment by iamchathu** [comment]
Just go to settings and select master branch for pages.

**Comment by iamchathu** [comment]
I just tested and send you a pull request too. http://chathu.me/Personal-Template/

**Comment by iamchathu** [comment]
Please add 'hacktoberfest' lable to my pull request.
Thank you.

**Comment by frkn-aydn** [comment]
I created github page. 

This : https://birz4man.github.io/Personal-Template/

**Comment by iamchathu** [comment]
Now just edit your repository description and add https://birz4man.github.io/Personal-Template/ to the website url

**Comment by frkn-aydn** [comment]
Okey i did :)

**Comment by iamchathu** [comment]
Do the change in here

<img width="1017" alt="screen shot 2016-10-13 at 1 41 44 pm" src="https://cloud.githubusercontent.com/assets/3932230/19341380/d636738e-914a-11e6-806f-8e478fabfeda.png">

**Comment by iamchathu** [comment]
If you can please create a new lable in issues called 'hacktoberfest' and add that label to my pull requests. Thank you.

**Comment by frkn-aydn** [comment]
There is no "hacktoberfest" in label options.

**Comment by iamchathu** [comment]
In here you can create new labels

https://github.com/birz4man/Personal-Template/labels

**Comment by frkn-aydn** [comment]
ok i did :)

**Comment by iamchathu** [comment]
Thanks. Will add More SEO related stuff soon

**Comment by frkn-aydn** [comment]
Thank you :)
