### ISSUE TITLE
Add Licence File

### ISSUE THREAD

**Issue by iamchathu** [birz4man/Personal-Template#2]
Add a licence to repository so others can contribute or use this.

**Comment by frkn-aydn** [comment]
Okey :) But how ?  I dont know how to create lisans.

**Comment by iamchathu** [comment]
https://help.github.com/articles/open-source-licensing/#how-can-i-go-back-through-my-public-repositories-and-give-them-licenses

**Comment by iamchathu** [comment]
I sent you pull request to this also

**Comment by frkn-aydn** [comment]
Okey no problem :) i marge your pull request :)
